name: Upload Source ZIP

on:
  release:
    types: [created]

jobs:
  upload-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to upload release assets

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Zip source code with version
      run: |
        mkdir -p dist
        zip -r dist/source-${{ github.event.release.tag_name }}.zip . -x '*.git*' 'dist/*' '.github/*'

    - name: Upload ZIP to GitHub Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/pop-analysis-${{ github.event.release.tag_name }}.zip
        asset_name: Source Code (zip)
        asset_content_type: application/zip